name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: danmathews575
          svg_out_path: ./output/github-contribution-grid-snake.svg
      - uses: Platane/snk@v3
        with:
          github_user_name: danmathews575
          svg_out_path: ./output/github-contribution-grid-snake-dark.svg
          theme: dark
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: ./output/*.svg
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update snake animation'
          add: './output/*.svg'
